ap_hero/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @ApiResource
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"product", "user", "supplier", "variant"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups({"product", "user", "supplier", "variant"})
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     * @Groups({"product", "user", "supplier", "variant"})
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     * @Groups({"product", "user", "supplier", "variant"})
     */
    private $username;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     * @Groups({"product", "user", "supplier", "variant"})
     */
    private $isBanned;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Pics", cascade={"persist", "remove"})
     * @ApiSubresource
     */
    private $avatar;

    /*
     * @ORM\OneToOne(targetEntity="App\Entity\Cart", mappedBy="user", orphanRemoval=true)
     * 
     */
    //private $cart;


    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Cart", mappedBy="user", cascade={"persist", "remove"})
     * @Groups({"product", "user", "supplier", "variant"})
     * @ApiSubresource
     */
    private $cart;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Metadata", mappedBy="user")
     * @Groups({"product", "user", "supplier", "variant", "metadata"})
     * @ApiSubresource
     */
    private $metadata;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Supplier", inversedBy="users")
     * @Groups({"product", "user", "variant"})
     */
    private $supplier;

    public function __construct()
    {
        $this->datetime = new ArrayCollection();
        $this->products = new ArrayCollection();
        $this->metadata = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getIsBanned(): ?bool
    {
        return $this->isBanned;
    }

    public function setIsBanned(?bool $isBanned): self
    {
        $this->isBanned = $isBanned;

        return $this;
    }

    public function getAvatar(): ?Pics
    {
        return $this->avatar;
    }

    public function setAvatar(?Pics $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): self
    {
        $this->cart = $cart;

        // set (or unset) the owning side of the relation if necessary
        $newUser = $cart === null ? null : $this;
        if ($newUser !== $cart->getUser()) {
            $cart->setUser($newUser);
        }

        return $this;
    }

    /**
     * @return Collection|Metadata[]
     */
    public function getMetadata(): Collection
    {
        return $this->metadata;
    }

    public function addMetadata(Metadata $metadata): self
    {
        if (!$this->metadata->contains($metadata)) {
            $this->metadata[] = $metadata;
            $metadata->setUser($this);
        }

        return $this;
    }

    public function removeMetadata(Metadata $metadata): self
    {
        if ($this->metadata->contains($metadata)) {
            $this->metadata->removeElement($metadata);
            // set the owning side to null (unless already changed)
            if ($metadata->getUser() === $this) {
                $metadata->setUser(null);
            }
        }
        return $this;
    }

    public function getSupplier(): ?Supplier
    {
        return $this->supplier;
    }

    public function setSupplier(?Supplier $supplier): self
    {
        $this->supplier = $supplier;

        return $this;
    }
}

ap_hero/src/Controller/ProductController.php
<?php
	/**
     * HomePage Controller
     *
     * This controller manage all about Home page
     *
     * @package      Some Package
     * @subpackage   Some Subpackage
     * @category     Home Page
     * @author       War Machines
     */
namespace App\Controller;

use App\Entity\CartItem;
use App\Entity\Nutritionals;
use App\Entity\Product;
use App\Entity\Variant;
use App\Entity\Pics;
use App\Entity\Stock;
use App\Form\ProductType;
use App\Form\CartItemType;
use App\Repository\ProductRepository;
use App\Service\Serializer\SerializerService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/product")
 */
class ProductController extends AbstractController
{
    /**
     * index
     * @Route("/", name="product_index", methods={"GET"})
     * @param  App\Repository\ProductRepository $productRepository
     *
     * @return Response
     */
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('product/index.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }

    /**
     * new
     * @Route("/new", name="product_new", methods={"GET","POST"})
     * @param  Symfony\Component\HttpFoundation\Request $request
     *
     * @return Symfony\Component\HttpFoundation\Response
     */
    public function new(Request $request): Response
    {
        $product = new Product();
        $user = $this->getUser();
        $greaterRole = (in_array('ROLE_ADMIN', $user->getRoles())) ? 'ROLE_ADMIN' : 'ROLE_SUPPLIER';
        $form = $this->createForm(ProductType::class, $product, ['role' => $greaterRole]);
        if ($greaterRole === 'ROLE_SUPPLIER') {
            $supplier = $user->getSupplier();
            $form->get('supplier')->setData($supplier);
        }
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $picFile = $form->get('picture')->getData();
            if ($picFile) {
                $picture = new Pics();
                $newFilename = $this->savePicture($picFile);
                $picture->setB64($newFilename);
                $product->setPicture($picture);
            }
            $nutritionals = $this->hydrateNutritionals($form);
            $product->setNutritionals($nutritionals);
            $product->setSupplier($form->get('supplier')->getData());
            $entityManager = $this->getDoctrine()->getManager();
            $this->addVariants($product, $entityManager);
            $entityManager->persist($product);
            $entityManager->flush();
            return $this->redirectToRoute('product_index');
        }
        return $this->render('product/new.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * show
     * @Route("/{id}", name="product_show", methods={"GET"})
     * @param  App\Entity\Product $product
     *
     * @return Symfony\Component\HttpFoundation\Response
     */
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    /**
     * getProduct
     * @Route("/api/{id}", name="product_show", methods={"GET"})
     * @param  App\Entity\Product $product
     *
     * @return Symfony\Component\HttpFoundation\Response
     */
    public function getProduct(Product $product, SerializerService $serializer): Response
    {
        // return $this->render('product/show.html.twig', [
        //     'product' => $product,
        // ]);
        // $products = $productRepository->findAll();
        return JsonResponse::fromJsonString($serializer->serializeEntity($product, 'product'));
    }

    /**
     * edit
     * @Route("/{id}/edit", name="product_edit", methods={"GET","POST"})
     * @param  Symfony\Component\HttpFoundation\Request $request
     * @param  App\Entity\Product $product
     *
     * @return Symfony\Component\HttpFoundation\Response
     */
    public function edit(Request $request, Product $product): Response
    {
        $greaterRole = (in_array('ROLE_ADMIN', $this->getUser()->getRoles())) ? 'ROLE_ADMIN' : 'ROLE_SUPPLIER';
        $form = $this->createForm(ProductType::class, $product, ['role' => $greaterRole]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $picFile = $form->get('picture')->getData();
            if ($picFile) {
                $picture = new Pics();
                $newFilename = $this->savePicture($picFile);
                $picture->setB64($newFilename);
                $product->setPicture($picture);
            }
            $nutritionals = $this->hydrateNutritionals($form);
            if ($nutritionals) {
                $product->setNutritionals($nutritionals);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $this->addVariants($product, $entityManager);
            $entityManager->flush();
            return $this->redirectToRoute('product_index');
        }

        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * delete
     * @Route("/{id}", name="product_delete", methods={"DELETE"})
     * @param  Symfony\Component\HttpFoundation\Request $request
     * @param  App\Entity\Product $product
     *
     * @return Symfony\Component\HttpFoundation\Response
     */
    public function delete(Request $request, Product $product): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('product_index');
    }

    /**
     * savePicture
     * @param string $pictureFile
     *
     * @return void
     */
    private function savePicture($pictureFile)
    {
        $originalFilename = pathinfo($pictureFile->getClientOriginalName(), PATHINFO_FILENAME);
        $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
        $newFilename = $safeFilename.'-'.uniqid().'.'.$pictureFile->guessExtension();

        try {
            $pictureFile->move(
                $this->getParameter('pics_directory'),
                $newFilename
            );
        } catch (FileException $e) {
            // ... handle exception if something happens during file upload
        }

        return $newFilename;
    }

    /**
     * hydrateNutritionals
     * @param  App\Form\ProductType $form
     *
     * @return void
     */
    private function hydrateNutritionals($form)
    {
        $nutritionals = new Nutritionals();
        $prots = $form->get('proteins')->getData();
        $carbs = $form->get('carbohydrates')->getData();
        $sugar = $form->get('sugar')->getData();
        $fat = $form->get('fat')->getData();
        $saturated = $form->get('saturated')->getData();
        $sodium = $form->get('sodium')->getData();
        if ($prots && $carbs && $fat && $sugar && $saturated && $sodium) {
            $nutritionals->setProtein($prots);
            $nutritionals->setCarbohydrates($carbs);
            $nutritionals->setFat($fat);
            $nutritionals->setSugar($sugar);
            $nutritionals->setTransAG($saturated);
            $nutritionals->setSalt($sodium);
            $nutritionals->setKCal(($prots + $carbs) * 4 + $fat * 9);
            $nutritionals->setKJ($nutritionals->getKCal() * 4,184);
            return $nutritionals;
        }
        return null;
    }

    /**
     * addVariants
     *
     * @param  App\Entity\Product $product
     * @param  Doctrine\ORM\EntityManagerInterface  $entityManager
     *
     * @return void
     */
    private function addVariants($product, $entityManager)
    {
        foreach($product->getVariants() as $variant) {
            if ($variant->getStock() === null) {
                $stock = new Stock();
                $stock->setQuantity(0);
                $variant->setStock($stock);
                $entityManager->persist($variant);
            }
        }
    }
}

ap_hero/templates/product/_delete_form.html.twig
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn btn-primary btn-sm">SUPPRIMER</button>
</form>

ap_hero/templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <a href="#" id="add_variant" class="btn btn-default">Add a variant</a>
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        var $container = $('div#product_variants');
        var index = $container.find(':input').length;

    $('#add_variant').click(function(e) {
        addVariant($container);

        e.preventDefault();
        return false;
    });

    if (index == 0) {
        addVariant($container);
    } else {
        $container.children('div').each(function() {
        addDeleteLink($(this));
      });
    }

    function addVariant($container) {
        var template = $container.attr('data-prototype')
                                .replace(/__name__label__/g, 'Variant N°' + (index+1))
                                .replace(/__name__/g,        index);

        var $prototype = $(template);
        addDeleteLink($prototype);
        $container.append($prototype);
        index++;
    }

    function addDeleteLink($prototype) {
        var $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');
        $prototype.append($deleteLink);
        $deleteLink.click(function(e) {
            $prototype.remove();
            e.preventDefault();
            return false;
        });
    }
  });
</script>

ap_hero/templates/product/edit.html.twig
{% extends 'basePhp.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <h1>Edit Product</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('product_index') }}">back to list</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}

ap_hero/templates/product/index.html.twig
{% extends 'basePhp.html.twig' %}

{% block title %}Product index{% endblock %}

{% block body %}
    <h1>Product index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Category</th>
                <th>Name</th>
                <th>Description</th>
                {# <th>Prix unitaire</th>
                <th>Stock</th> #}
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                {% if product.category is not null %}
                    <td>{{ product.category.name }}</td>
                {% endif %}
                <td>{{ product.name }}</td>
                <td>{{ product.description }}</td>
                {# <td>{{ product.price }}</td> #}
                {# <!--{% if product.stock is not null %}
                    {% if product.stock.quantity > 0 %}
                        <td>{{ product.stock.quantity }} U </td>
                        <td>
                            <form action="{{ path('cart_item_add', {'id': product.id, 'quantity': 1}) }}" method="post">
                                <input name="{{ product.id }}" type="number" step="1" min="1" max="{{ product.stock.quantity }}" value="1"/>
                                <input type="submit" value="Add to cart"/>
                            </form>
                        </td>
                    {% else %}
                        <td>En rupture de stock !</td>
                    {% endif %}
                {% else %}
                    <td>En rupture de stock !</td>
                {% endif %} -->#}
                {% if is_granted("ROLE_ADMIN") %}
                <td>
                    <a href="{{ path('product_show', {'id': product.id}) }}">show</a>
                    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>
                </td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('product_new') }}">Create new</a>
{% endblock %}

ap_hero/templates/product/new.html.twig
{% extends 'basePhp.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('product_index') }}">back to list</a>
{% endblock %}

ap_hero/templates/product/show.html.twig
{% extends 'basePhp.html.twig' %}

{% block body %}
    <section class="p-t-30">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="post">
                        <div class="post-header">
                            <div></div>
                            <div>
                                <h2 class="post-title">
                                    {{ product.name }}
                                </h2>
                                <div class="post-meta">
                                    <span>
                                        <i class="fas fa-utensils"></i>
                                        {{ product.Category.name }}
                                    </span>
                                    <p>
                                        {% for allergen in product.allergens %}
                                            Allergènes :
                                            {{ allergen.name }}
                                        {% else %}
                                            {{ "Ne contient pas de produits allergènes." }}
                                        {% endfor %}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="post-thumbnail">
                            {% if product.picture is not null %}
                                <div class="embed-responsive embed-responsive-16by9">
                                    <img class="embed-responsive-item" src="{{ product.picture.b64 }}">
                                </div>
                            {% endif %}
                        </div>
                        {% if product.variants is not null %}
                            {% for variant in product.variants %}
                                <hr/>
                                <ul class="d-flex flex-row-reverse">
                                    <li>
                                        <form action="{{ path('cart_item_add', {'id': variant.id, 'quantity': 1.0}) }}" method="post">
                                            <i class="fas fa-dolly"></i>
                                            {{ variant.stock.quantity }}
                                            <button type="submit" class="btn btn-primary btn-sm" style="width:140px">
                                                <i class="fas fa-shopping-cart"></i>
                                                {{ variant.name }}
                                                à
                                                {{ variant.price }}€
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="sidebar">
                        {% if product.nutritionals is not null %}
                            <h4>valeurs nutriotionnelles moyennes pour 100g</h4>
                            <div class="widget">
                                <h5 class="widget-title">Energie (KJ) :
                                    {{ product.nutritionals.kJ }}</h5>
                            </div>
                            <div class="widget">
                                <h5 class="widget-title">Energie (KCal) :
                                    {{ product.nutritionals.KCal }}</h5>
                            </div>
                            <div class="widget">
                                <h5 class="widget-title">Proteines :
                                    {{ product.nutritionals.protein }}</h5>
                            </div>
                            <div class="widget">
                                <h5 class="widget-title">Carbohydrates :
                                    {{ product.nutritionals.carbohydrates }}</h5>
                            </div>
                            <div class="widget">
                                <h5 class="widget-title">Sucre :
                                    {{ product.nutritionals.sugar }}</h5>
                            </div>
                            <div class="widget">
                                <h5 class="widget-title">Matière grasse :
                                    {{ product.nutritionals.fat }}</h5>
                            </div>
                            <div class="widget">
                                <h5 class="widget-title">dont acides gras saturés :
                                    {{ product.nutritionals.transAG }}</h5>
                            </div>
                            <div class="widget">
                                <h5 class="widget-title">Sel :
                                    {{ product.nutritionals.salt }}</h5>
                            </div>
                        {% endif %}
						{% if is_granted('ROLE_ADMIN') %}
                        <ul class="d-flex flex-row">
                            <button class="btn btn-secondary btn-sm">
                                <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>
                            </button>
                            {{ include('product/_delete_form.html.twig') }}
                        </ul>
						{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}